### ISSUE TITLE
Introduction to github issues

### ISSUE THREAD

**Issue by iimpulse** [gdancik/hello_world#2]
Hi @gdancik !

Great program. It would be great if you could print the first and last name in the output!

This would be a great way to demonstrate pull requests and how they relate to issues that are used often in the github site!

As well as using the items on the left to add assignees, projects, labels, and milestones. -->
--Mike

**Comment by gdancik** [comment]
You know it! Didn't we do this when you were in Senior Research? Hope everything is going well.
